Add basic support for Météo France API
geometric-weather-foss/GeometricWeather pull request #10
Opened 2020-11-01 14:39 UTC by papjul

Météo France is the French national meteorological service.
Here is a basic support for their unofficial API.

What works:
- Search for a location (query or coordinates)
- Daily forecast for the next 15 days
- Hourly forecast
- Humidity
- Clouds
- Sunset and sunrise
- Partial support for wind
- Partial support for rain
- Partial support for official authorities weather warnings
- French translation was improved and completed

What does not work/is not available yet:
- There is no Air Quality data. This is the same as AccuWeather (there is no Air Quality support for France). However, Météo France uses Air Parif data to display air quality information in their official app so we might use this in the future, although it only works for "Île de France" region so it's only a minor addition to look forward to.
- There is a "Feels like null" displayed. This is a bug at app level (we need to add "when feels_like is null, do not display").
- Rain for the next 60 minutes: this is one of the first things that I wish to add for the supported cities.
- Warnings do not work if using current location with GPS instead of manual location, because app is using data from Accu Weather instead of Météo France and Accu Weather does not process regions the same way (warnings are issued "region"-wide). App has a strange way of mixing location searches through all providers. We may be able to counter this by getting the "domain" returned by the daily forecast "position" information and then make an additional API call.
- The "night time" information only contains the temperature, the rest is not available with daily API. We should be able to retrieve it through the hourly weather data but this will only cover about 7 days (hourly forecast does not go beyond), not the whole 15 days. So we need to address this at app level (make night @Nullable and "if HalfDay night is null, do not display night information in daily chart").
- Complete support for wind with the hourly weather data, because it is not available at all in the daily weather data from API. Same way of proceeding as above.
- Moonset and moonrise: this information is only available for the current day with an additional API query, so we may be able to add it in the future. Not really urgent.

To sum up, some minor things are missing from the set of data Météo France provides for free, so we don't have a full set of data in Geometric Weather, unlike what is possible Accu Weather, but Météo France data is still more accurate (in France), so adding this API is a good addition to this wonderful app.

I added the "(beta)" keyword to the weather data provider name due to the few things that need to be addressed, but in the meantime everything in the "What works" section should already be sufficient for daily usage.

Note: I had to update GreenDAO module because I could not compile it otherwise.

2020-11-02 16:44 UTC, mbestavros commented
@papjul This is absolutely awesome! Thanks for the contribution.

I'd encourage you to propose this [upstream](https://github.com/WangDaYeeeeee/GeometricWeather) so people who have the app through the Play Store also have this option. 

If they end up not being responsive, I'd be happy to add this to my fork in some way.

BTW, we should connect about further enhancements -- I'd love to get another "broad-spectrum" API available as an alternative to AccuWeather, like [OpenWeatherMap](https://openweathermap.org/). I gave it a stab, but didn't make much progress. If you'd be willing to give that a try as well, that would be fantastic.

2020-11-02 20:22 UTC, papjul commented
Thank you for your support!

I'm not sure about upstream, many things were removed in your version, which would prove difficult to maintain in two different versions (mainly due to provider list being different and being heavily tied to the core of the app, as opposed to providers as extensions (check the way [Tachiyomi extensions](/inorichi/tachiyomi-extensions) work for example)), especially since there are no tests. It would require manual testing in the two versions, notably in one that I do not plan to use at all: people installing the original version are probably more interested by the Chinese providers.

For Play Store users, the question would more likely be: should we maintain this fork as a different "Western" app? So it could be published through Play Store (similar to Vinyl Music Player vs Phonograph).
There has not been a lot of commits recently on the original Geometric Weather so we can still cherry-pick some commits from time to time.

I can probably help on OpenWeatherMap. Implementing the Météo France API happened to be very easy, it requires no Android knowledge, just some basic Java (and some copy/paste/adapt from the already existing API). The most difficult part is the availability of data since Geometric Weather requires a lot of mandatory data which is not always available.

After seeing so many junk weather apps, having one that just does its job without a clunky interface, and open source, feels so good, so I'm willing to spend some time enhancing it. We can connect but I don't know what's the best way for a small team today, I know there are some cool open source projects out there for this (Mattermost, Element, etc) or we can just use some Discord, please let me know your choice.

2020-11-03 15:33 UTC, mbestavros commented
@papjul All great questions/points! I'll try setting a project chat up this weekend (that's right up my alley) and we can discuss further.

> After seeing so many junk weather apps, having one that just does its job without a clunky interface, and open source, feels so good, so I'm willing to spend some time enhancing it.

You read my mind! Exactly why I'm so interested in making this a thing.

2020-12-20 15:54 UTC, mbestavros commented
@papjul I'm on my holiday break, so I've finally found the time to actually do what I said 😅 

I created a community and room on matrix.org where we can chat: https://matrix.to/#/+geometric-weather-foss:matrix.org

Hope to see you there! We can discuss other contribution details as well. I'm also going to try and figure out a good way to merge and release this on the F-Droid app, since it's really good work.

2020-12-27 03:46 UTC, mbestavros requested changes
@papjul Thanks so much for the continued cooperation in getting this merge-ready! I've done one final review -- you introduced a lot of spacing changes in this PR that, while I agree are good, would probably be best introduced as a separate patch. As-is, it means that there are lots of files where the only modification is just a newline inserted at the end, which is bad for auditability.

Given that, I have two requests for changes:

1: Could you edit your first commit to remove these spacing changes? I've highlighted them inline.
2: Could you edit the wording of your first commit to better reflect the (tremendous) work done? Right now it just reads as "Start implementing some things". Something like "Implement beta support for Meteo France API" would be perfect.

If that's done, I think this looks good to go, and will happily merge -- very excited 😄

2020-12-27 03:46 UTC, mbestavros commented on app/src/main/java/wangdaye/com/geometricweather/basic/model/option/utils/OptionMapper.java
> +
I'd prefer we not introduce spacing changes in large commits/PRs like this. Could you remove these from your first commit?

2020-12-27 03:46 UTC, mbestavros commented on app/src/main/java/wangdaye/com/geometricweather/basic/model/option/utils/OptionMapper.java
> +
Remove spacing, please.

2020-12-27 03:46 UTC, mbestavros commented on app/src/main/java/wangdaye/com/geometricweather/basic/model/option/utils/OptionMapper.java
> +
Remove spacing, please.

2020-12-27 03:46 UTC, mbestavros commented on app/src/main/java/wangdaye/com/geometricweather/basic/model/option/utils/OptionMapper.java
> +
Remove spacing, please.

2020-12-27 03:46 UTC, mbestavros commented on app/src/main/java/wangdaye/com/geometricweather/basic/model/option/utils/OptionMapper.java
> +
Remove spacing, please.

2020-12-27 03:46 UTC, mbestavros commented on app/src/main/java/wangdaye/com/geometricweather/location/LocationHelper.java
> +}
I appreciate adding newlines is a good thing, but perhaps in a separate commit.

2020-12-27 03:46 UTC, mbestavros commented on app/src/main/res/values-cs/arrays.xml
> +</resources>
Same here -- ending newlines are good, but in a separate commit/PR.

2020-12-27 03:46 UTC, mbestavros commented on app/src/main/res/values-ja/arrays.xml
> +</resources>
Remove this newline, please.

2020-12-27 03:46 UTC, mbestavros commented on app/src/main/res/values-ko/arrays.xml
> +</resources>
Remove this newline, please.

2020-12-27 03:46 UTC, mbestavros commented on app/src/main/res/values-pl/arrays.xml
> +</resources>
Remove this newline, please.

2020-12-27 03:46 UTC, mbestavros commented on app/src/main/res/values-ru/arrays.xml
> +</resources>
Remove this newline, please.

2020-12-27 03:46 UTC, mbestavros commented on app/src/main/res/values-zh-rCN/arrays.xml
> +</resources>
Remove this newline, please.

2020-12-27 03:46 UTC, mbestavros commented on app/src/main/res/values-zh-rHK/arrays.xml
> +</resources>
Remove this newline, please.

2020-12-27 03:46 UTC, mbestavros commented on app/src/main/res/values-zh-rTW/arrays.xml
> +</resources>
Remove this newline, please.

2020-12-27 03:46 UTC, mbestavros commented on app/src/main/res/values/arrays.xml
> +</resources>
Remove this newline, please.

2020-12-27 03:46 UTC, mbestavros commented on gradle.properties
> +android.enableJetifier=true
Remove this newline, please.

2020-12-27 15:44 UTC, mbestavros approved these changes
I've changed my mind about the spacing changes -- they're too annoying to undo, and I'd like to get this merged in so @papjul can get cracking on other things. The commit wording looks good now, so I think this PR is ready to go!

2020-12-27 15:45 UTC, merged